### ISSUE TITLE
solve github actions windows native-tls build

### ISSUE THREAD

**Issue by clux** [kube-rs/kube-rs#566]
Problems with the github actions ci setup from #562 (which ALMOST gets a working windows build!) is that `openssl` is either too slow to install, or it slows down all the other jobs.

Options considered:

- ❌ adding openssl vendored feature everywhere (but slows down linux builds between 30-80%)
- ❌ adding openssl vendored under a cfg.windows config (but this requires [resolver2](https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2))
- ❌ switching to [resolver2](https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2) (but this make every crate herein unbuildable with `cargo build` because we can't select an `k8s-openapi` feature as a dependency - see [features2#drawbacks](https://rust-lang.github.io/rfcs/2957-cargo-features2.html#drawbacks))
- ❌ adding a [plain vcpkg install](https://github.com/sfackler/rust-openssl/blob/c65d85afc9a0af5f0b03a5424b346a85f709b122/.github/workflows/ci.yml#L78-L90) (but this adds 6minutes to the windows build (other cached actions are 3min vs. 9min on windows (even after disabling parts of the tests))
- ❓adding [run-vcpkg](https://github.com/marketplace/actions/run-vcpkg) caching action for a smarter openssl install (but we haven't made this work yet, and have not managed to fix yet ([furthest result](https://github.com/clux/kube-rs/runs/2903061264?check_suite_focus=true)))
- ❓adding a `native-tls-vendored` feature and forking the matrix job to special-case invoke the vendored feature (a bit of work but is doable, some unknown w.r.t. what -vendored libraries to use, follow [reqwest with native-tls/vendored?](https://github.com/seanmonstar/reqwest/blob/b9cf2db69756cde5e3091cc6a06cff1deb2e3764/Cargo.toml#L38))

Stashing down this because we would like to solve windows CI, but in a time/cache-efficient setup so that we don't have these enormous cycles just because of it.

### sketches
vcpkg caching sketch:

```yaml
      - name: Windows vcpkg install openssl and cache
        uses: lukka/run-vcpkg@v6
        if: matrix.os == 'windows-latest'
        with:
          vcpkgArguments: 'openssl:x64-windows'
          vcpkgDirectory: '${{ runner.workspace }}/b/vcpkg'
          vcpkgGitCommitId: 'master'
```

with `VCPKGRS_DYNAMIC: 1` evar, was the furthest the caching one got.
