### ISSUE TITLE
Skip serializing None values in Kubeconfig

### ISSUE THREAD

**Issue by xrl** [kube-rs/kube-rs#612]
I am building a tool for upserting configs in to my kube user's `~/.kube/config` file. I read in the file, munge it up, then reserialize the `Kubeconfig` with `serde_yaml` but I'm getting a ton of `~` values that really blow up the line count.

For example, it outputs:

```
    user:
      username: ~
      password: ~
      token: ~
      tokenFile: ~
      client-certificate: ~
      client-certificate-data: ~
      client-key: ~
```

would we be OK with taking:

```
#[derive(Clone, Debug, Serialize, Deserialize, Default)]
pub struct AuthInfo {
    /// The username for basic authentication to the kubernetes cluster.
    pub username: Option<String>,
    /// The password for basic authentication to the kubernetes cluster.
    pub password: Option<String>,

    /// OMIT
}
```

and making it something like

```
#[derive(Clone, Debug, Serialize, Deserialize, Default)]
pub struct AuthInfo {
    /// The username for basic authentication to the kubernetes cluster.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    /// The password for basic authentication to the kubernetes cluster.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,

    /// OMIT
}
```

which would then just skip the field at serialize time
