### ISSUE TITLE
Cannot deserialize a serialized AdmissionReview (auditAnnotations is missing)

### ISSUE THREAD

**Issue by awoimbee** [kube-rs/kube-rs#936]
### Current and expected behavior

I am writing tests for my webhooks, so I need to deserialize the `AdmissionReview`s that I produce using this lib.
Turns out that at serialization this lib omits `auditAnnotations` when it's empty, but then it can't deserialize because `auditAnnotations` is missing.

Workaround:
```rust
let mut val = resp.json::<serde_json::Value>().await.unwrap();
// Fixes "missing field"
val["response"]["auditAnnotations"] = serde_json::to_value(HashMap::<String, String>::new()).unwrap();
let review: AdmissionReview<Pod> = serde_json::from_value(val).unwrap();
let response = review.response.unwrap();
```

### Additional context

Thanks for the awesome crate ;)

### Environment

no cluster nor dockerfile

### Configuration and features

```toml
kube = {version="0.73", features=["admission"]}
k8s-openapi = {version="0.15.0", features=["v1_23"]}
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
```

### Affected crates

kube-core

### Would you like to work on fixing this bug?

maybe
