### ISSUE TITLE
The `CustomResourceExt` trait isn't properly imported

### ISSUE THREAD

**Issue by ereOn** [kube-rs/kube-rs#962]
### Current and expected behavior

I'm trying to make use of the CRD generation feature, that is part of the `CustomResourceExt`.

Here is my very simple program:

```rust
use kube::{core::CustomResourceExt, CustomResource};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use validator::Validate;

#[derive(CustomResource, Debug, Clone, Deserialize, Serialize, Validate, JsonSchema)]
#[kube(group = "test.com", version = "v1", kind = "Book")]
pub struct BookSpec {
    #[validate(length(min = 3))]
    pub title: String,
}

#[tokio::main]
async fn main() {
    println!("crd: {}", serde_yaml::to_string(&BookSpec::crd()).unwrap()); // crd yaml
}
```

This is supposed to work as per the docs, but it gives me the following error:

![image](https://user-images.githubusercontent.com/585131/179994350-7ec167ed-5fe9-4fb6-8605-f55535280f44.png)

### Possible solution

I have not found a solution.

### Environment

Client Version: v1.24.1
Kustomize Version: v4.5.4
Server Version: v1.24.1

### Configuration and features

```toml
[dependencies]
kube = { version = "0.74.0", default-features = false, features = [
    "client",
    "derive",
    "runtime",
    "rustls-tls",
] }
schemars = "0.8"
validator = { version = "0.15.0", features = ["derive"] }
k8s-openapi = { version = "0.15.0", features = ["v1_24"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
tokio = { version = "1.20.0", features = ["full"] }
```

### Affected crates

kube-core, kube-derive

### Would you like to work on fixing this bug?

maybe
